### ISSUE TITLE
Colour code output

### ISSUE THREAD

**Issue by mattmole** [jvns/dig-pretty#1]
Just a thought, how about using the Python Rich library to add some colour coding to the output?

https://rich.readthedocs.io/en/stable/introduction.html

Thanks for your work on this, making the output more readable is a good idea

**Comment by jvns** [comment]
Added some more colour to the output in e1b68ecd1038f76b4498387605cbf176aa03d4bf. I don't really want to add another dependency so I just added more colours to the `color` function. 

I'll close for now but happy to accept more ideas for places to add colour 🌈 . Here's what it looks like right now:
<img width="653" alt="Screenshot 2023-07-30 at 10 06 36 PM" src="https://github.com/jvns/dig-pretty/assets/817739/4969a2d2-1055-4b52-a4fe-0f2a4820e37e">

**Comment by mattmole** [comment]
Great. That looks to add some clarity and as you say, saves another library just to set some colours
